export const objApi = {
  Header: {
    nav: ["home", "movies", "tv-series", "documents", "top IMDB"],
    navDisplay: [
      {
        head: "Captain America: winter soldier",
        quality: "HD",
        rate: "8.6",
        duration: "130",
        genre: ["Action", "Sci-fi"],
        description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero
        dolores obcaecati optio id voluptas est eos, delectus quibusdam`,
      },
    ],
  },
  movies: [
    {
      title: "Bullet Train",
      img: "/images/bullet-train-movie.jpg",
      year: "2022",
      duration: "126 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "The Princess",
      img: "/images/the-princess-movie.jpg",
      year: "2022",
      duration: "94 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Top Gun:Maverick",
      img: "/images/top-gun-maverick-movie-poster-6207.jpg",
      year: "2022",
      duration: "130 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Pinocchio",
      img: "/images/pinocchio-2022-movie.jpg",
      year: "2022",
      duration: "110 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Morbius",
      img: "/images/morbius-movie-poster-6498.jpg",
      year: "2022",
      duration: "108 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Scream",
      img: "/images/scream-2022-movie-poster-6686.jpg",
      year: "2022",
      duration: "126 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Uncharted",
      img: "/images/uncharted-movie-poster-6522.jpg",
      year: "2022",
      duration: "116 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "The Bad Guys",
      img: "/images/the-bad-guys-movie-poster-6781.jpg",
      year: "2022",
      duration: "140 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Thirteen Lives",
      img: "/images/thirteen-lives-movie-poster-6992.jpg",
      year: "2022",
      duration: "142 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Resident Evil: Welcome to Raccon City",
      img: "/images/resident-evil-welcome-to-raccoon-city-.jpg",
      year: "2021",
      duration: "107 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Opration Fortune:Ruse de Guerre",
      img: "/images/operationfortune-ruse-de-guerre-movie-poster-6864.jpg",
      year: "2022",
      duration: "98 min",
      quality: "HD",
      type: "Movie",
    },
    {
      title: "Clifford The big Red",
      img: "/images/clifford-the-big-read-dog-movie-poster-6695.jpg",
      year: "2022",
      duration: "97 min",
      quality: "HD",
      type: "Movie",
    },
  ],
  tv: [
    {
      title: "Peaky Blinders",
      img: "/images/peaky-blinder.jpg",
      year: "2013",
      duration: "6 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "Friends",
      img: "/images/friends.jpg",
      year: "1994",
      duration: "10 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "Family Guy",
      img: "/images/Family_Guy_TV_Series.jpg",
      year: "1999",
      duration: "21 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "The Big Bang Theory",
      img: "/images/the-big-bang.jpg",
      year: "2007",
      duration: "21 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "See",
      img: "/images/see.jpg",
      year: "2022",
      duration: "3 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "How I Met Your Mother",
      img: "/images/HIMYM.jpg",
      year: "2005",
      duration: "9 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "The Walking Dead",
      img: "/images/walking-dead.jpg",
      year: "2010",
      duration: "5 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "Breaking Bads",
      img: "/images/breaking-bad.jpg",
      year: "2008",
      duration: "5 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "Game Of Thrones",
      img: "/images/got.jpg",
      year: "2011",
      duration: "8 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "The Blacklist",
      img: "/images/black-list.jpg",
      year: "2013",
      duration: "9 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "Lucifer",
      img: "/images/lucifer.jpg",
      year: "2016",
      duration: "6 Seasons",
      quality: "HD",
      type: "TV",
    },
    {
      title: "The Last Kingdom",
      img: "/images/last-kingdom.jpg",
      year: "2015",
      duration: "5 Seasons",
      quality: "HD",
      type: "TV",
    },
  ],
  documentary: [
    {
      title: "The Staircase",
      img: "/images/true-crime.jpg",
      year: "2022",
      duration: "1 Season",
      quality: "True Crime",
      type: "HD",
    },
    {
      title: "I Am a Killer",
      img: "/images/iamakiller.jpg",
      year: "2018",
      duration: "3 Seasons",
      quality: "DOC",
      type: "HD",
    },
  ],
};
